[package]
name = "project_x_core"
description = "Project X: the foundation for the whole game."
version = "0.0.1"
authors = ["pierreyoda <pierreyoda@users.noreply.github.com>"]
edition = "2021"
readme = "README.md"

[lib]
path = "src/lib.rs"

[dependencies]
